### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by tommasotoffanin** [p-costa/CaNS#37] opened 2022-10-17 14:41 UTC
Good evening,

I have a problem while running 
##### ./cans 
I get by output 
![erroreCaNS](https://user-images.githubusercontent.com/116007125/196205544-c1669613-9947-45b6-80f1-76004319fd73.png)
I currently use WSL2 and 20.04.4 LTS Ubuntu version, both of them are 64bit, and so it is the cans file. 
Could you please help me out?
Thank you so much,
Tommaso

**Comment by p-costa** [comment] 2022-10-17 14:47
Hello @tommasotoffanin,

CaNS relies on MPI, and the binary should run using `mpirun`. I'm assuming you have MPI installed, since you were able to compile the code, so would something like`mpirun ./cans` work?

Thanks!
Pedro

**Comment by tommasotoffanin** [comment] 2022-10-17 15:04
Good evening Pedro,

Thank you for your reply. Sadly using `mpirun ./cans` or `mpirun -np 8 ./cans` I get this output
![cansmpirun](https://user-images.githubusercontent.com/116007125/196211837-907c468a-acc7-4a5b-9e0a-b65a35340c48.png)
I don't get how to fix that error,
Tommaso

**Comment by p-costa** [comment] 2022-10-17 15:19
Ok, then let me ask for some more details:

What would be the output of:

 * `which mpif90`
 * `which mpirun`
 * `echo $LD_LIBRARY_PATH`
 * `echo $CPATH`
 * `echo $PATH`

Did you compile CaNS using the default `build.conf` file? Could you clear the compilation with `make allclean` and paste here the output of `make libs && make`?

Thanks!
Pedro

PS: Instead of using screenshots, you can also paste the output directly here by sandwiching the output you get with triple quotes; see [here](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

**Comment by p-costa** [comment] 2022-10-17 15:22
Another question: did you compile CaNS on the same (operating) system where you are running the executable?
Thanks!

**Comment by tommasotoffanin** [comment] 2022-10-17 19:25
Good evening Pedro,
so the outputs are, by order:

- `/usr/bin/mpif90`
- `/usr/bin/mpirun`
- `/opt/ThirdParty-9/platforms/linux64Gcc/gperftools-svn/lib:/opt/openfoam9/platforms/linux64GccDPInt32Opt/lib/paraview-5.6:/opt/paraviewopenfoam56/lib:/opt/openfoam9/platforms/linux64GccDPInt32Opt/lib/openmpi-system:/opt/ThirdParty-9/platforms/linux64GccDPInt32/lib/openmpi-system:/usr/lib/x86_64-linux-gnu/openmpi/lib:/home/tom/OpenFOAM/tom-9/platforms/linux64GccDPInt32Opt/lib:/opt/site/9/platforms/linux64GccDPInt32Opt/lib:/opt/openfoam9/platforms/linux64GccDPInt32Opt/lib:/opt/ThirdParty-9/platforms/linux64GccDPInt32/lib:/opt/openfoam9/platforms/linux64GccDPInt32Opt/lib/dummy`
- (`echo $CPATH` has no output)
- `/opt/ThirdParty-9/platforms/linux64Gcc/gperftools-svn/bin:/opt/paraviewopenfoam56/bin:/opt/ThirdParty-9/platforms/linux64Gcc/cmake-*/bin:/home/tom/OpenFOAM/tom-9/platforms/linux64GccDPInt32Opt/bin:/opt/site/9/platforms/linux64GccDPInt32Opt/bin:/opt/openfoam9/platforms/linux64GccDPInt32Opt/bin:/opt/openfoam9/bin:/opt/openfoam9/wmake:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program:Files/MSC.Software/NaPa_SE/20211/Patran/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program:Files:(x86)/NVIDIA:Corporation/PhysX/Common:/mnt/c/Program:Files/NVIDIA:Corporation/NVIDIA:NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program:Files/MATLAB/R2020b/bin:/mnt/c/Users/Negro/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/AppData/Local/Programs/Microsoft:VS:Code/bin:/snap/bin`

Also, my Fluid Dynamics Professor compiled it with `make libs && make` using **macOS**, and then he shared his folder with me. On the other hand I use Windows 11, and the output of `make libs && make`, after cleaning the compilation, is:
`/bin/bash: ./src/.gen-deps.awk: Permission denied
cd ./dependencies/2decomp-fft && make
make[1]: Entering directory '/home/tom/CaNS-main/dependencies/2decomp-fft'
fatal: not a git repository (or any of the parent directories): .git
echo "FC = mpifort" > Makefile.settings
echo "FFLAGS =  -cpp -O3 -march=native -J mod -Imod" >> Makefile.settings
echo "OPT =  " >> Makefile.settings
echo "DEFS = -DVERSION=\"\" -DDOUBLE_PREC -cpp" >> Makefile.settings
echo "INC =  " >> Makefile.settings
echo "LIBOPT = rcs" >> Makefile.settings
echo "LIBFFT = " >> Makefile.settings
echo "LFLAGS = " >> Makefile.settings
mpifort  -cpp -O3 -march=native -J mod -Imod   -DVERSION=\"\" -DDOUBLE_PREC -cpp   -c src/decomp_2d.f90 -o obj/decomp_2d.o
mpifort  -cpp -O3 -march=native -J mod -Imod   -DVERSION=\"\" -DDOUBLE_PREC -cpp   -c src/d2d_log.f90 -o obj/d2d_log.o
mpifort  -cpp -O3 -march=native -J mod -Imod   -DVERSION=\"\" -DDOUBLE_PREC -cpp   -c src/io.f90 -o obj/io.o
mpifort  -cpp -O3 -march=native -J mod -Imod   -DVERSION=\"\" -DDOUBLE_PREC -cpp   -c src/./glassman.f90 -o obj/./glassman.o
mpifort  -cpp -O3 -march=native -J mod -Imod   -DVERSION=\"\" -DDOUBLE_PREC -cpp   -c src/fft_generic.f90 -o obj/fft_generic.o
ar rcs libdecomp2d.a obj/decomp_2d.o obj/d2d_log.o obj/io.o obj/./glassman.o obj/fft_generic.o
make[1]: Leaving directory '/home/tom/CaNS-main/dependencies/2decomp-fft'
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/chkdiv.f90.o src/chkdiv.f90
src/chkdiv.f90:9:6:`

    9 |   use mod_common_mpi, only: ierr
      |      1
`Fatal Error: Cannot open module file ‘mod_common_mpi.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [Makefile:86: src/chkdiv.f90.o] Error 1`

Thank you very much,
Tommaso

**Comment by p-costa** [comment] 2022-10-17 20:08
Thank you for checking the outputs, Tommaso @tommasotoffanin.

Unfortunately, I do not have access to a Windows system, and I am afraid that an executable compiled at macOS won't work on Windows. I should try to get access to a Windows machine to try to get CaNS working there.

Still, I see that the 2decomp&fft submodule was not copied into your system. Instead of downloading the repository, could you clone it directly from the command line as follows:
```
git clone --recursive https://github.com/CaNS-World/CaNS
```
If all goes well, the folder under `dependencies/2decomp-fft/` should not be empty.

Then, if you don't mind, could you try to compile the 2decomp library using `make libs`? And if that goes well, then you can try to compile CaNS with `make`, but I see already that there is an issue with the `.gen_deps.awk` file, so I will probably need to look into that.

Thanks in advance!
Pedro

**Comment by tommasotoffanin** [comment] 2022-10-18 08:10
Good moring Pedro,

thanks for your advices, I cloned the repository and checked the folder ` dependencies/2decomp-fft/` and it's not empty. I used `make libs` and this is the output:
`echo "FC = mpifort" > Makefile.settings
echo "FFLAGS =  -cpp -O3 -march=native -J mod -Imod" >> Makefile.settings
echo "OPT =  " >> Makefile.settings
echo "DEFS = -DVERSION=\"aadd7b1\" -DDOUBLE_PREC -cpp" >> Makefile.settings
echo "INC =  " >> Makefile.settings
echo "LIBOPT = rcs" >> Makefile.settings
echo "LIBFFT = " >> Makefile.settings
echo "LFLAGS = " >> Makefile.settings
make: *** No rule to make target 'libs'.  Stop.`
Then I tried to compile CaNS with `make` but it didn't go well:
`mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/common_mpi.f90.o src/common_mpi.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/types.f90.o src/types.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/param.f90.o src/param.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/initflow.f90.o src/initflow.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/mom.f90.o src/mom.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/scal.f90.o src/scal.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/common_cudecomp.f90.o src/common_cudecomp.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/utils.f90.o src/utils.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/rk.f90.o src/rk.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/fftw.f90.o src/fftw.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/fft.f90.o src/fft.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/initsolver.f90.o src/initsolver.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/chkdiv.f90.o src/chkdiv.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
mpifort  -O3 -cpp  -D_DEBUG -D_TIMING -D_DECOMP_X  -I./dependencies/2decomp-fft/mod -J ./src -c -o src/initmpi.f90.o src/initmpi.f90
f951: Warning: Nonexistent include directory ‘./dependencies/2decomp-fft/mod’ [-Wmissing-include-dirs]
src/initmpi.f90:9:6:`

    9 |   use decomp_2d
      |      1
`Fatal Error: Cannot open module file ‘decomp_2d.mod’ for reading at (1): No such file or directory
compilation terminated.
make: *** [Makefile:86: src/initmpi.f90.o] Error 1`
I tried then again and this time it shows a different error, when I try to compile CaNS:
`mpifort  -O3 src/initflow.f90.o src/initsolver.f90.o src/rk.f90.o src/scal.f90.o src/mom.f90.o src/initmpi.f90.o src/workspaces.f90.o src/sanity.f90.o src/output.f90.o src/chkdt.f90.o src/load.f90.o src/utils.f90.o src/nvtx.f90.o src/fillps.f90.o src/fft.f90.o src/gpu_utils.f90.o src/main.f90.o src/debug.f90.o src/common_mpi.f90.o src/solver.f90.o src/bound.f90.o src/common_cudecomp.f90.o src/initgrid.f90.o src/fftw.f90.o src/timer.f90.o src/updatep.f90.o src/correc.f90.o src/post.f90.o src/param.f90.o src/chkdiv.f90.o src/types.f90.o src/solver_gpu.f90.o  -L./dependencies/2decomp-fft -ldecomp2d -lfftw3  -I./dependencies/2decomp-fft/mod -o ./run/cans
/usr/bin/ld: cannot find -lfftw3
collect2: error: ld returned 1 exit status
make: *** [Makefile:77: run/cans] Error 1`

Thank you very much,
Tommaso

**Comment by p-costa** [comment] 2022-10-18 08:42
Hello Tommaso,

Thank you! I am afraid I do not have a way of testing things out on WSL2, right now. I am going to ask a colleague. I just have another minor question, if you don't mind. What is the version of GNU make on your system? You can check it with:
```
make --version
```
Thanks!
Pedro

**Comment by tommasotoffanin** [comment] 2022-10-18 09:02
Good morning Pedro,

Thank you for your help. I checked the version of GNU make and it is:
`GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>`

Thank you,
Tommaso

**Comment by p-costa** [comment] 2022-10-18 11:30
Thank you, @tommasotoffanin. I asked a colleague for help installing this version of Ubuntu via WSL2, and then I will try to reproduce the error.

In the meantime, have you considered other options for running Linux on Windows, such as a virtual machine? See, for instance, section 3 in this [link](https://www.onmsft.com/how-to/install-ubuntu-on-windows-10-or-windows-11).

**Comment by p-costa** [comment] 2022-10-18 13:47
Hi @tommasotoffanin,

A colleague here was very kind to test this on his Windows system. On a fresh install of Ubuntu on Windows via WSL2, he took the following steps:

```
# ----------- install wsl ubuntu -----------
```

```
#     (run in windows cmd as administrator)
#     (reboot computer after installation)
wsl --install
```

```
# ----------- inside ubuntu terminal -----------
```

```
# 1) update apt
sudo apt     update
sudo apt     upgrade
sudo apt-get update
sudo apt-get upgrade
```

```
# 2) libraries
sudo apt          install make
sudo apt-get      install gfortran
sudo apt-get -y   install openmpi-bin
sudo apt-get      install libfftw3-dev libfftw3-doc
```

```
# 3) clone repository
git clone --recursive https://github.com/CaNS-World/CaNS
```

```
# 5) compile code
cd ${HOME}/CaNS
make allclean
make libs && make
```

Do these work for you?

Pedro

**Comment by tommasotoffanin** [comment] 2022-10-18 14:56
Good afternoon Pedro,

Thank you very much for your help and thank your kind colleague for me. 
I tried with **VirtualBox** but it gave the same error outputs. Then I followed the steps provided by your colleague and it worked. I started the simulation with `./cans` and everything worked out. There's just one more problem, when I run **ParaView** to visualize the results of the simulation, as I select the `viewfld_DNS.xmf` file, **ParaView** crashes and the output is `Segmentation fault`. Do you know why this happens?

Thank you very much,
Tommaso

**Comment by p-costa** [comment] 2022-10-18 15:19
Glad we got this to work.

There could be many reasons for the paraview crash you report (e.g., lack of resources), as the reported error is quite generic. Are you running Paraview from Windows? Thanks!

**Comment by tommasotoffanin** [comment] 2022-10-18 15:23
Good afternoon Pedro,

I'm running **ParaView** from Ubuntu via WSL2. This morning I updated Ubuntu from 20.04.4 to 22.04.1. Could that be a problem?

Thank you very much,
Tommaso

**Comment by p-costa** [comment] 2022-10-18 15:29
Does it work if you install paraview on Windows and load the `.bin` and `.xmf` files using that install (i.e., open paraview, then do file...open... viewfld_DNS.xmf)

Pedro

PS: I think the original issue is settled, so we could close this issue and follow up by e-mail, or in the [discussions](https://github.com/CaNS-World/CaNS/discussions).

**Comment by tommasotoffanin** [comment] 2022-10-18 15:50
Good afternoon Pedro,
ok, I'll try to install it on Windows and I'll let you know in the discussions or by e-mail.
The original issue is fixed yes, thank you very much for your help and for your colleague's help!
Tommaso

**Closed as completed** 2022-10-18 15:52 UTC
